use_frameworks!

platform :ios, '9.0'

target 'StarPopover_Example' do
  pod 'StarPopover', :path => '../'

  target 'StarPopover_Tests' do
    inherit! :search_paths
  end
  
  post_install do |installer|
      # 全部支持支持版本
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "9.0"
      end
    end
  end
end
